sudo: required
dist: trusty
language: python
python:
  - "3.7"
  - "3.6"

env:
  matrix:
    - _TF_VERSION=1.13.1
    - _TF_VERSION=1.12.2
  global:
    - KERAS_BACKEND=tensorflow

# command to install dependencies
install:
    - python -m pip install -r requirements.txt
    - |
      if [ -z "_TF_VERSION" ]
      then
        python -m pip install tensorflow
      else
        python -m pip install tensorflow==$_TF_VERSION
      fi
# commands to run tests
script:
    - cd tests
    - ./test_all.sh
