sudo: yes
dist: xenial
language: python
install: python -m pip install -r requirements.txt

jobs:
  allow_failures:
    - name: Integration Tests
  include:
    - name: Unit Tests </> Python 3.7
      python: 3.7
      script:
          - cd tests
          - ./test_all.sh
    - name: Integration Tests </> Python 3.7
      python: 3.7
      script:
          - cd tests
          - ./test_all.sh
    - name: Unit Tests </> Python 3.6
      python: 3.6
      script:
          - cd tests
          - ./test_all.sh
    - name: Integration Tests </> Python 3.6
      python: 3.6
      script:
          - cd tests
          - ./test_all.sh

    - stage: GitHub Release
      python: 3.6
      if: tag IS present AND branch = master
      script: echo "Deploying to GitHub releases ..."
      before_deploy: python3 setup.py sdist bdist_wheel
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file_glob: true
        file:
          - "dist/tml-*.whl"
          - "dist/tml-*.tar.gz"
        skip_cleanup: true
        on:
          tags: true
