sudo: yes
dist: xenial
language: python

# command to install dependencies
install:
    - python -m pip install -r requirements.txt
jobs:
  allow_failures:
    - name: Integration Tests
  include:
    # - stage: Tests
      # commands to run tests
    - script:
          - cd tests
          - ./test_all.sh
      name: Unit Tests
      python: 3.6
    - script:
          - cd tests
          - ./test_all.sh
      name: Integration Tests
      python: 3.6
    - stage: GitHub Release
      if: tag IS present
      python: 3.6
      script: echo "Deploying to GitHub releases ..."
      before_deploy: python3 setup.py sdist bdist_wheel
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file_glob: true
        file:
          - "dist/tml-*.whl"
          - "dist/tml-*.tar.gz"
        skip_cleanup: true
        on:
          tags: true
