sudo: yes
dist: xenial
language: python
install: python -m pip install -r requirements.txt

# matrix
python:
  - 3.7
  - 3.6

# test scripts
script: cd tests; ./test_all.sh

stages:
  - name: Unit Tests
  - name: Integration Tests
    if: type != pull
  - name: Deploy

# release
jobs:
  allow_failures:
    - stage: Integration Tests
  include:
    - stage: Unit Tests
      script: cd tests; ./test_all.sh

    - stage: Integration Testss
      script: cd tests; ./test_all.sh

    - stage: Deploy
      if: tag IS present AND branch = master
      script: echo "Deploying to GitHub releases ..."
      before_deploy: python3 setup.py sdist bdist_wheel
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file_glob: true
        file:
          - "dist/tml-*.whl"
          - "dist/tml-*.tar.gz"
        skip_cleanup: true
        on:
          tags: true
