sudo: required
dist: trusty
language: python
python:
  - "3.6"
  - "3.5"

env:

  matrix:
#     - _TF_VERSION=1.10.1 # Remove on Apr 28, 2019
#     - _TF_VERSION=1.9.0 # Remove on Apr 28, 2019
#     - _TF_VERSION=1.8.0 # Remove on Apr 28, 2019
#     - _TF_VERSION=1.7.1 # Remove on May 08, 2019
    - _TF_VERSION=1.7.0 # Remove on Mar 29, 2019
    - _TF_VERSION=1.6.0 # Remove on Mar 01, 2019
global:
  - KERAS_BACKEND=tensorflow

# command to install dependencies
install:
    - python -m pip install tensorflow==$_TF_VERSION
    - python -m pip install -r requirements.txt
# commands to run tests
script:
    - cd tests
    - ./test_all.sh
