sudo: yes
dist: xenial
language: python
install: python -m pip install -r requirements.txt
python: 3.6

jobs:
  include:
    - name: Unit Tests
      script:
          - cd tests
          - ./test_all.sh
    - name: Integration Tests
      script:
          - cd tests
          - ./test_all.sh

    - stage: GitHub Release
      if: tag IS present AND branch = master
      script: echo "Deploying to GitHub releases ..."
      before_deploy: python3 setup.py sdist bdist_wheel
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file_glob: true
        file:
          - "dist/tml-*.whl"
          - "dist/tml-*.tar.gz"
        skip_cleanup: true
        on:
          tags: true
    allow_failures:
      - name: Integration Tests
