sudo: yes
dist: xenial
language: python
install: python -m pip install -r requirements.txt

# matrix
python:
  - 3.7
  - 3.6
env:
  - TEST_TYPE=UNIT_TEST
  # - TEST_TYPE=INTEGRATION_TEST

matrix:
  include:
    - env: TEST_TYPE=INTEGRATION_TEST
      if: type != pull
  allow_failures:
    - env: TEST_TYPE=INTEGRATION_TEST

# test scripts
script:
  - if [ "$TEST_TYPE" = "UNIT_TEST" ]; then cd tests; ./test_all.sh; fi
  - if [ "$TEST_TYPE" = "INTEGRATION_TEST" ]; then cd tests; ./test_all.sh; fi

# release
jobs:
  include:
    - if: type != push
      env: TEST_TYPE=INTEGRATION_TEST
    - stage: deploy
      if: tag IS present AND branch = master
      script: echo "Deploying to GitHub releases ..."
      before_deploy: python3 setup.py sdist bdist_wheel
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file_glob: true
        file:
          - "dist/tml-*.whl"
          - "dist/tml-*.tar.gz"
        skip_cleanup: true
        on:
          tags: true
