language: python
python:
  - "3.6"
# command to install dependencies
install:
  - sudo pip3 install -r requirements.txt
# commands to run tests
script:
  - cd tests
  - python3 collector_test.py
  - ./test_preprocessing.sh
