language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install --upgrade tensorflow
# commands to run tests
script:
  - cd tests
  - python3 collector_test.py
  - ./test_preprocessing.sh
