sudo: yes
dist: xenial
language: python
python:
  # - "3.7"
  - "3.6"

env:
  matrix:
    - _TF_VERSION=1.13.1
  global:
    - KERAS_BACKEND=tensorflow

# command to install dependencies
install:
    - python -m pip install -r requirements.txt
    - |
      if [ -z "_TF_VERSION" ]
      then
        python -m pip install tensorflow
      else
        python -m pip install tensorflow==$_TF_VERSION
      fi
# commands to run tests
script:
    - cd tests
    - ./test_all.sh
jobs:
  include:
    - stage: GitHub Release
      python: 3.6
      script: echo "Deploying to GitHub releases ..."
      before_deploy: python3 setup.py sdist bdist_wheel
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file_glob: true
        file:
          - "dist/tml-*.whl"
          - "dist/tml-*.tar.gz"
        skip_cleanup: true
        on:
          tags: true
